apiVersion: v1
kind: Pod
metadata:
  name: scenario-demo-nginx-priv-sa
spec:
  containers:
  - name: scenario-demo-nginx-priv-sa
    image: nginx
    securityContext:
      privileged: True
  serviceAccountName: scenario-demo-tester-sa